---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/shortcodes
  label: Shortcodes
  create: all
  match: "**/*"
- type: directory
  path: content/content-organization
  label: Content organization
  create: all
  match: "**/*"
- type: directory
  path: content/create-page
  label: Create page
  create: all
  match: "**/*"
- type: directory
  path: content/getting-start
  label: Getting start
  create: all
  match: "**/*"
- type: directory
  path: content/search
  label: Search
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.51'
